name: PHP Composer

on:
  push:
    branches: [ main ]

jobs:
  php-unit-test:
    runs-on: ubuntu-latest

    env:
        AAPANEL_URL: ${{ secrets.AAPANEL_URL }}
        AAPANEL_API_KEY: ${{ secrets.AAPANEL_API_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          extensions: mbstring, json, intl, curl

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Run PHPUnit tests
        run: vendor/bin/phpunit --configuration phpunit.xml
